#!/usr/bin/env python3
# Anti-alias decimation FIR for the AY channel of the PSP port.
#
# The PSP block generator produces output samples directly at 44100 Hz,
# while the AY chip is stepped at its own rate of 218750 Hz
# (1.5 MHz * 14 / 96). The old code box-averaged the ~5 chip samples of
# each output period; a box that short has its first null at ~44 kHz, so
# every AY harmonic between 22 kHz (output Nyquist) and 109 kHz (chip
# Nyquist) folds back into the audible band as hiss.
#
# This script designs a windowed-sinc (Blackman) low-pass that runs on the
# chip-rate sample stream and is evaluated once per output sample. It cuts
# everything above the output Nyquist before decimation.
#
# Pure stdlib (math) only: numpy/scipy are not required.
#
#   python3 filters/ay_decim.py
#
# Writes psp/src/ay_decim_coef.h

import math
import os

TAPS = 128               # power of two -> cheap circular-buffer masking
CHIP_RATE = 218750.0     # AY chip step rate (1.5 MHz * 14 / 96)
OUT_RATE = 44100.0       # PSP output rate
# Pass-band edge as a fraction of the chip rate. 0.082 * 218750 = 17.9 kHz,
# just below the 22.05 kHz output Nyquist, keeping the AY bright while the
# Blackman transition (~6 kHz at 128 taps) pushes the stop band to ~24 kHz.
FC = 0.082

OUT_PATH = os.path.join(os.path.dirname(__file__), "..", "psp", "src",
                        "ay_decim_coef.h")


def design(taps, fc):
    m = taps - 1
    h = []
    for n in range(taps):
        x = n - m / 2.0
        # ideal low-pass impulse response (cutoff fc, in cycles/sample)
        sinc = 2.0 * fc if x == 0.0 else math.sin(2.0 * math.pi * fc * x) / (math.pi * x)
        # Blackman window
        w = (0.42
             - 0.50 * math.cos(2.0 * math.pi * n / m)
             + 0.08 * math.cos(4.0 * math.pi * n / m))
        h.append(sinc * w)
    # unity DC gain: the AY level (0..3) must be preserved exactly
    s = sum(h)
    return [v / s for v in h]


def main():
    h = design(TAPS, FC)
    with open(OUT_PATH, "w") as f:
        f.write("/* Generated by filters/ay_decim.py - do not edit by hand.\n")
        f.write(" * Blackman-windowed sinc anti-alias FIR for the AY channel.\n")
        f.write(" *   taps      = %d\n" % TAPS)
        f.write(" *   chip rate = %.0f Hz\n" % CHIP_RATE)
        f.write(" *   cutoff    = %.0f Hz (-6 dB)\n" % (FC * CHIP_RATE))
        f.write(" *   out rate  = %.0f Hz\n" % OUT_RATE)
        f.write(" * Unity DC gain (coefficients sum to 1).\n")
        f.write(" */\n")
        f.write("#pragma once\n\n")
        f.write("#define AY_DECIM_TAPS %d\n\n" % TAPS)
        f.write("static const float ay_decim_coef[AY_DECIM_TAPS] = {\n")
        for i in range(0, TAPS, 4):
            row = ", ".join("% .8f" % h[k] for k in range(i, min(i + 4, TAPS)))
            f.write("    " + row + ",\n")
        f.write("};\n")
    print("wrote %s (%d taps, sum=%.6f)" % (os.path.normpath(OUT_PATH), TAPS, sum(h)))


if __name__ == "__main__":
    main()
